### ISSUE TITLE
Not rendering SVG

### ISSUE THREAD

**Issue by mahemoff** [carrot/share-button#219] opened 2015-09-17 10:45 UTC
I did a standard install with CSS and JS (no Entypo as I don't think it's necessary anymore?) and no config options.

The share button pops up without icons:
![](http://i.imgur.com/gPXlukc.jpg)

I'm seeing errors like this in devtools:
![](http://i.imgur.com/b3xM1SI.jpg)

**Comment by gurumark** [comment] 2015-09-17 14:07
+1

**Comment by hhsnopek** [comment] 2015-09-17 14:14
Which browser is this in?



--
Henry Snopek

**Comment by gurumark** [comment] 2015-09-17 14:15
Firefox 40.0.3 on OSX 10.10

**Comment by mahemoff** [comment] 2015-09-18 02:33
Chrome stable too (M45)

**Comment by hhsnopek** [comment] 2015-09-18 02:58
when you hover over the icon what's the message? I'm currently looking at master with Chrome (45.0.2454.93 ) and Canary (47.0.2511.3 canary) and both render this properly. However in Firefox (40.0.3) and FireFoxDeveloperEdition (42.0a2 (2015-08-18)) it isn't, after doing some research in firefox they do not support the "#" unless encoded as "%23". Also didn't realize that <= IE11 the whole string must be encoded. I'll get a PR going for these two fixes

**Comment by mahemoff** [comment] 2015-09-18 03:29
"Invalid property value".

Is there a working demo? As the linked one at http://sharebutton.co/ I think is using the old Entypo model. 

[Here's a JSBin illustrating the problem](http://jsbin.com/weluzi/1/edit?html,css,output)

![](https://i.imgur.com/Ft2u7oW.jpg)

**Comment by mahemoff** [comment] 2015-09-18 05:29
Actually it may be related to the use of double-quotes.

The JSBin does work once I fixed up quote marks (the background property is valid though I can't see it in the web page). http://jsbin.com/weluzi/3/edit?html,css,output

Likewise, in the [CSS](https://github.com/carrot/share-button/blob/20bda0323be187d463dca04af4f7e00caf9978eb/dist/styles.css#L235), it looks like double-quotes are nested, I presume there be escaping or single quotes used to avoid that.

**Comment by mahemoff** [comment] 2015-09-18 05:40
Yes, that fixed it! I simply changed the surrounding double-quotes to single quotes, ie from `url("data ... </svg>") to `url('data ... </svg>')`.

I see the Stylus already contains single-quotes, but the CSS in dist/ uses double-quotes?

**Comment by hhsnopek** [comment] 2015-09-18 08:24
Yeah so only compile stylus changes this over, not sure why



--
Henry Snopek

**Comment by hhsnopek** [comment] 2015-09-18 17:46
Excuse the strange grammer, it was pretty late when I sent that. Basically stylus is processing the single quotes into double quotes. Locally when I was adjusting styles, encoding the `#` within the color made it viewable again. ![facebook fixed](https://cldup.com/X8R8egsizb.png) in the compiled source everything is still double quoted.  As the quotes are [technically optional](http://www.w3.org/TR/CSS2/syndata.html#value-def-uri) we could remove them from our stylus, but this results in errors from stylus.

**Comment by hafi86** [comment] 2015-09-21 19:25
hey, i was having the same problem, i finally was able to solve it with those two changes:
1. converting all "data...." into single quote, like you guys suggested (thanks!), but that wasn't enough in my case, so i got to stage 2:
2. adding 
  top:12px;
  left:30px;
in the same css file, to the class "share-button .sb-social ul li:before,
share-button .sb-social ul li:after"

only than the icons appeared.
hope this helps someone... :)

**Comment by mahemoff** [comment] 2015-09-22 14:57
@hafi86 Strange; I have it [in production now](https://player.fm/series/this-week-in-tech-mp3) using only the single-quote change.

**Comment by mahemoff** [comment] 2015-09-22 14:59
BTW I'm leaving this open though maybe only a patch to stylus would fix it? (short of a hacky post-processing string replace)

**Comment by hhsnopek** [comment] 2015-09-22 15:02
I'm thinking of switching the preprocessor (stylus) of to postcss or just creating a mixin to overwrite 'url()' which would then use JavaScript to remove quotes and encode the string with 'encodeComponentURI()'.



--
Henry Snopek

**Comment by hhsnopek** [comment] 2015-09-22 19:54
got stylus and jade mixed up, your right it would have to use a post processing hack... I'm thinking of just moving this into postcss now

**Comment by hafi86** [comment] 2015-09-23 19:58
Yes, i find it strange too, but changing to signle-quote only helped for the icon on the button itself (the one that shows on the button before clicking 'share'), not sure why.
Thank you for your help.

**Comment by hhsnopek** [comment] 2015-09-24 01:55
I have a fix locally for this, I'll get this up within the next couple hours

**Comment by hhsnopek** [comment] 2015-09-24 17:49
@mahemoff wanna take a look at #227 before I merge?

**Comment by raulhuelamo** [comment] 2015-09-27 19:12
Hi guys, I had issues today with SVG in Firefox (I started using the plugin yesterday), reviewed the quotation fix method and didn't work.
I found this solution in StackOverflow (http://stackoverflow.com/a/21626701) that actually makes the whole sense, removing every problem related with quotations just doing some pre-process with the SVG code (Base64 encoding).
It worked like a charm for me, so I hope you find this useful guys

**Closed** 2015-09-28 20:08 UTC

**Comment by Exclam** [comment] 2016-04-28 06:13
I had the same issues with Chrome today. I solved it (but only for Chrome) by urldecode the SVG in the css and set the width and height to 100%. Maybe the issue is caused by the frameworks I use around. eg. Flexbox.

Unfortunately it doesn't run now in Firefox and Safari :)
Used in basket view of http://www.love-o-mat.de/

**Comment by natecook** [comment] 2016-05-03 19:57
Ya, [the example](https://sharebutton.co/) seems to be broken again. It's not displaying the SVGs for me in Chrome Version 50.0.2661.94 (64-bit) and on MacBook Pro OS X Yosemite 10.10.5

**Comment by perjonsson** [comment] 2016-05-07 10:52
Same here. Chrome 50.0.2661.94 on El Captain 10.11.1. Any news on this?

**Comment by natecook** [comment] 2016-05-13 14:24
@perjonsson you may find an answer over at [this issue](https://github.com/carrot/share-button/issues/305). I ended up downloading the svg's and then referencing those instead of the data uri. 
Another guy said he did the same on the other issue.
